### ISSUE TITLE
button changed callback called twice

### ISSUE THREAD

**Issue by amiceli** [fehmer/adafruit-i2c-lcd#13]
When button state is detected, callback is called twice, with the example code :

    lcd.on('button_change', function(button) {
        console.log (button);
    });

When I pressed button, consol.log is twice displayed.

Thank you for your help

**Comment by fehmer** [comment]
hi @amiceli,

thank you for your message.

There are three different events you can listen to:

- button_change: firing on button press and release
- button_down: firing on button press
- button_up: firing on button release

its in the [documentation](https://github.com/fehmer/adafruit-i2c-lcd#events) directly under the example for button_change. 

I hope this will solve your problem,

grtz christian

**Comment by amiceli** [comment]
Thank you it works perfectly now !

Sorry I should read the doc.
