### ISSUE TITLE
i2c-bus v4.x.x request

### ISSUE THREAD

**Issue by meeki007** [fehmer/adafruit-i2c-lcd#14]
nodeJS 10 is now the Long term support branch.
current depend is for i2c-bus is v1.x.x and only supports nodeJS 9 or less.

request higher dependency.

**Comment by fehmer** [comment]
Hi @meeki007,

thank you for reporting the issue. Unfortunately i currently don't have access to the required hardware to work on the update of the i2c-bus dependency.

If you want to contribute please prepare a PR for a 2.0.0 version including some documentation about the mininum node version needed for the new release. 

cheers, christian

**Comment by meeki007** [comment]
Need you to create a new branch called 1.0.x so I can pull request changes to it and then the new master.

**Comment by fehmer** [comment]
Thanks to @aphotix for updating to i2c-bus 5.1.0.
