### ISSUE TITLE
ascii char

### ISSUE THREAD

**Issue by Kepro** [fehmer/adafruit-i2c-lcd#5]
Hi, if i try to show message with ASCII char they don't work (work but show not good)
i have try utf-8 but not working... i must change coding of file or on your library we can do change? :) thanks

**Comment by fehmer** [comment]
I just checked the python library again. The newer version supports the creation of custom characters:
```python
lcd.create_char(1, [2, 3, 2, 2, 14, 30, 12, 0])
lcd.message('RED \x01')
```

I'll try to implement this feature into the library.

**Comment by fehmer** [comment]
Hi @Kepro,

i added support for custom characters to version 1.0.1:

```javascript
lcd.createChar(1, [0,0,10,31,31,14,4,0]);
lcd.createChar(2, [0,4,10,17,17,10,4,0]);

lcd.clear();
lcd.backlight(lcd.colors.RED);
lcd.message('I\x01 n\x02de.js', true);
```

**Comment by Kepro** [comment]
@fehmer  thanks!
