### ISSUE TITLE
backlight does not work with the Sainsmart 16x2 i2c - semi-clone

### ISSUE THREAD

**Issue by saraf** [fehmer/adafruit-i2c-lcd#8]
First off - I am using a Sainsmart display - http://www.amazon.com/SainSmart-Interface-Screen-Keypad-Raspberry/dp/B00SMHSTL0/ref=cm_cr_pr_product_top?ie=UTF8

that is almost a clone of the adafruit i2c 16x2 display - except that the RGB backlight commands do not actually change the lcd panel backlight, but there is an RGB LED -above- the LCD panel that changes color.

Now here is the problem - this node.js library does not turn the backlight on, but just sets the color of that RGB LED as shown here (and actually turns the LCD panel backlight OFF if it was on before) - 

``` javascript
var LCDPLATE, lcd;
LCDPLATE = require('adafruit-i2c-lcd').plate;
lcd = new LCDPLATE('/dev/i2c-1', 0x20);

lcd.backlight(lcd.colors.RED);
lcd.message('Goodbye World!');
```
![img_2213](https://cloud.githubusercontent.com/assets/117493/10079391/bcbbe2ea-6324-11e5-8610-2621703e1242.JPG)

Note that the backlight is off.
After exiting this node.js app, I run a small python script that just inits the LCD plate and exits.
This turns the LCD backlight on! 
I am using the example in https://github.com/adafruit/Adafruit_Python_CharLCD.git
```python
#!/usr/bin/python
# Example using a character LCD plate.
import time

import Adafruit_CharLCD as LCD


# Initialize the LCD using the pins
lcd = LCD.Adafruit_CharLCDPlate()
exit();
```
This has the effect of turning the LCD backlight on. 
![img_2212](https://cloud.githubusercontent.com/assets/117493/10079527/87c39154-6325-11e5-9dc7-f2f9333634ae.JPG)

Now if I run the node.js file again, it turns off the backlight that the python script had turned on.

There seems to be some slight difference between the manner in which the adafruit python library inits the display and the manner in which this node.js lib initializes it. What could it be?

**Comment by jnovack** [comment]
Found this on Amazon, but do not have a clue what it means.

> This thing works just like the Adafruit equivalent, with one catch. Instead of an RGB backlight, there's an RGB LED above the LCD, and the backlight is just a regular white backlight at fixed brightness. You _CAN_ use the Adafruit CharLCDPlate python library to control it, but you'll need to make a modification to turn the backlight on. On the I2C chip (MCP23017), the backlight is connected to GPA5, which is the 6th bit of port A. On the init and stop functions, you'll have to modify the IODIRA, IPOLA, GPPUA registers to set the bit to 0 instead of 1. Now, to turn on the backlight, you set the 6th bit of port A to 0, and to turn it off you set it to 1.

> Also note that you need to install some stuff and turn on i2c using raspi-config so that you can get i2c working in python on a pi, but you can google that.

> Source: http://www.amazon.com/review/R7XU6Y6KRZSLF/ref=cm_cr_dp_cmt?ie=UTF8&ASIN=B00SMHSTL0&channel=detail-glance&nodeID=16310091&store=industrial#wasThisHelpful

**Comment by jnovack** [comment]
**OR...**

You can toggle it in your client-side code.

    lcd.sendBytes(0, 0x00); // Backlight on
    lcd.sendBytes(0, 0x20); // Backlight off


-------------------

From your application, it's a simple call.

    var LCDPLATE = require('adafruit-i2c-lcd').plate;
    var lcd = new LCDPLATE('/dev/i2c-1', 0x20);
    lcd.message(new Date().toLocaleTimeString());
    lcd.sendBytes(0, 0x00);

**Comment by fehmer** [comment]
Hi @saraf, does the line provided by @jnovack solve your problem?

**Comment by saraf** [comment]
Thank you jnovack! That should do it!
Please give me a few days ... I cannot get near my pi right now.

**Comment by saraf** [comment]
Thank you jnovack - lcd.sendBytes(0, 0x00); // Backlight on
lcd.sendBytes(0, 0x20); // Backlight off

as well as 

lcd.sendBytes(0, 0x1F); // Backlight on
lcd.sendBytes(0, 0x3F); // Backlight off

both work.

thank you for taking the time to find and document this!
